<?php
/**
 * AddvideoserviceencodingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  de\addvideo\client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AddVideo REST API v1
 *
 * <h1>Willkommen bei AddVideo | add video to your project</h1><p>Nutzen Sie die Technologie von AddVideo zur Verbindung von CMS- mit CDN-Funktionalitäten. Mit AddVideo verarbeiten und distribuieren Sie Ihre Videoinhalte ganz nach Bedarf. Werden Sie und Ihre Anwendungen unabhängig von Oberflächen oder CDN-spezifischen Anforderungen. AddVideo bietet Ihnen:</p><ul><li>individuelle Nutzung durch Anbindung über Rest-API</li><li>Client SDKs in vielen Programmiersprachen frei verfügbar unter http://github.com/addvideo</li><li>Media Processing und Video Encoding Services</li><li>Betrieb und Datenhaltung in Rechenzentren in Deutschland</li><li>Service und Betrieb durch ein erfahrenes Team von Videospezialisten in Frankfurt am Main</li><li>einen stetig wachsenden Funktionsumfang</li><li>eine stetig wachsende Anzahl an angebundenen CDNs</li><li>Nutzung von zahlreichen OTT-Funktionen über die API</li></ul><p>Bei AddVideo können Sie individuell selbst entscheiden, welche Bausteine Sie für Ihre Videoverwaltung benötigen. Bestehende Systeme und Lösungen lassen sich komfortabel anbinden.</p>
 *
 * OpenAPI spec version: 1
 * Contact: info@addvideo.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace de\addvideo\client;

use \de\addvideo\client\Configuration;
use \de\addvideo\client\ApiClient;
use \de\addvideo\client\ApiException;
use \de\addvideo\client\ObjectSerializer;

/**
 * AddvideoserviceencodingApiTest Class Doc Comment
 *
 * @category Class
 * @package  de\addvideo\client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AddvideoserviceencodingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addEncodingService
     *
     * Add a new EncodingService object.
     *
     */
    public function testAddEncodingService()
    {

    }

    /**
     * Test case for addFFMPEGEncodingFlavor
     *
     * Add a new FFMPEGEncodingFlavor object.
     *
     */
    public function testAddFFMPEGEncodingFlavor()
    {

    }

    /**
     * Test case for deleteEncodingService
     *
     * Delete EncodingService object matching the given id.
     *
     */
    public function testDeleteEncodingService()
    {

    }

    /**
     * Test case for deleteFFMPEGEncodingFlavor
     *
     * Delete FFMPEGEncodingFlavor object matching the given id.
     *
     */
    public function testDeleteFFMPEGEncodingFlavor()
    {

    }

    /**
     * Test case for getEncodingService
     *
     * Get EncodingService object for id.
     *
     */
    public function testGetEncodingService()
    {

    }

    /**
     * Test case for getFFMPEGEncodingFlavor
     *
     * Get FFMPEGEncodingFlavor object for id.
     *
     */
    public function testGetFFMPEGEncodingFlavor()
    {

    }

    /**
     * Test case for listEncodingServices
     *
     * List EncodingService objects depending on filter.
     *
     */
    public function testListEncodingServices()
    {

    }

    /**
     * Test case for listFFMPEGEncodingFlavors
     *
     * List FFMPEGEncodingFlavor objects depending on filter.
     *
     */
    public function testListFFMPEGEncodingFlavors()
    {

    }

    /**
     * Test case for updateEncodingService
     *
     * Update EncodingService object.
     *
     */
    public function testUpdateEncodingService()
    {

    }

    /**
     * Test case for updateFFMPEGEncodingFlavor
     *
     * Update FFMPEGEncodingFlavor object.
     *
     */
    public function testUpdateFFMPEGEncodingFlavor()
    {

    }

}
