<?php
/**
 * AddvideoexportApiTest
 * PHP version 5
 *
 * @category Class
 * @package  de\addvideo\client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AddVideo REST API v1
 *
 * <h1>Welcome to AddVideo | easy video integration into your project</h1><p>AddVideo offers the integration of professional online video services and capabilities such as CDN, encoding, asset management and complex distribution workflows  with your favourite CMS. AddVideo processes and distributes your video contents as required, without interface- or CDN-specific implementations. Using AddVideo you will get:</p><ul><li>API: a powerful REST-API with free client SDKs available in many different programming languages incl. examples at http://github.com/addvideo</li><li>Encoding: media processing and video encoding services</li><li>CDN: use diverse very powerful global CDNs to distribute your contents</li><li>OTT: access to useful functionalities via the API</li><li>Development, Service und Maintenance: our team of high class software engineers and online video specialists is located in Frankfurt/Germany</li><li>Powerfull Infrastructure: system operations in high class data centres in Germany</li><li>In General: a fast growing set of features</li></ul><p>It has never been easier to add professional video modules to your platform on demand. AddVideo helps to slimline your integration efforts and provides the whole video workflow accessible through a simple programming interface.</p>
 *
 * OpenAPI spec version: 1
 * Contact: info@addvideo.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace de\addvideo\client;

use \de\addvideo\client\Configuration;
use \de\addvideo\client\ApiClient;
use \de\addvideo\client\ApiException;
use \de\addvideo\client\ObjectSerializer;

/**
 * AddvideoexportApiTest Class Doc Comment
 *
 * @category Class
 * @package  de\addvideo\client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AddvideoexportApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addFTPCompletedExport
     *
     * Add a new FTPCompletedExport object.
     *
     */
    public function testAddFTPCompletedExport()
    {

    }

    /**
     * Test case for addFTPExportConfig
     *
     * Add a new FTPExportConfig object.
     *
     */
    public function testAddFTPExportConfig()
    {

    }

    /**
     * Test case for addS3CompletedExport
     *
     * Add a new S3CompletedExport object.
     *
     */
    public function testAddS3CompletedExport()
    {

    }

    /**
     * Test case for addS3ExportConfig
     *
     * Add a new S3ExportConfig object.
     *
     */
    public function testAddS3ExportConfig()
    {

    }

    /**
     * Test case for deleteFTPCompletedExport
     *
     * Delete FTPCompletedExport object matching the given id.
     *
     */
    public function testDeleteFTPCompletedExport()
    {

    }

    /**
     * Test case for deleteFTPExportConfig
     *
     * Delete FTPExportConfig object matching the given id.
     *
     */
    public function testDeleteFTPExportConfig()
    {

    }

    /**
     * Test case for deleteS3CompletedExport
     *
     * Delete S3CompletedExport object matching the given id.
     *
     */
    public function testDeleteS3CompletedExport()
    {

    }

    /**
     * Test case for deleteS3ExportConfig
     *
     * Delete S3ExportConfig object matching the given id.
     *
     */
    public function testDeleteS3ExportConfig()
    {

    }

    /**
     * Test case for getFTPCompletedExport
     *
     * Get FTPCompletedExport object for id.
     *
     */
    public function testGetFTPCompletedExport()
    {

    }

    /**
     * Test case for getFTPExportConfig
     *
     * Get FTPExportConfig object for id.
     *
     */
    public function testGetFTPExportConfig()
    {

    }

    /**
     * Test case for getS3CompletedExport
     *
     * Get S3CompletedExport object for id.
     *
     */
    public function testGetS3CompletedExport()
    {

    }

    /**
     * Test case for getS3ExportConfig
     *
     * Get S3ExportConfig object for id.
     *
     */
    public function testGetS3ExportConfig()
    {

    }

    /**
     * Test case for listFTPCompletedExports
     *
     * List FTPCompletedExport objects depending on filter.
     *
     */
    public function testListFTPCompletedExports()
    {

    }

    /**
     * Test case for listFTPExportConfigs
     *
     * List FTPExportConfig objects depending on filter.
     *
     */
    public function testListFTPExportConfigs()
    {

    }

    /**
     * Test case for listS3CompletedExports
     *
     * List S3CompletedExport objects depending on filter.
     *
     */
    public function testListS3CompletedExports()
    {

    }

    /**
     * Test case for listS3ExportConfigs
     *
     * List S3ExportConfig objects depending on filter.
     *
     */
    public function testListS3ExportConfigs()
    {

    }

    /**
     * Test case for updateFTPCompletedExport
     *
     * Update FTPCompletedExport object.
     *
     */
    public function testUpdateFTPCompletedExport()
    {

    }

    /**
     * Test case for updateFTPExportConfig
     *
     * Update FTPExportConfig object.
     *
     */
    public function testUpdateFTPExportConfig()
    {

    }

    /**
     * Test case for updateS3CompletedExport
     *
     * Update S3CompletedExport object.
     *
     */
    public function testUpdateS3CompletedExport()
    {

    }

    /**
     * Test case for updateS3ExportConfig
     *
     * Update S3ExportConfig object.
     *
     */
    public function testUpdateS3ExportConfig()
    {

    }

}
