<?php
/**
 * AddvideoservicecdnApiTest
 * PHP version 5
 *
 * @category Class
 * @package  de\addvideo\client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AddVideo REST API v1
 *
 * <h1>Welcome!</h1><p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p><p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam</p><p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
 *
 * OpenAPI spec version: 1
 * Contact: info@addvideo.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace de\addvideo\client;

use \de\addvideo\client\Configuration;
use \de\addvideo\client\ApiClient;
use \de\addvideo\client\ApiException;
use \de\addvideo\client\ObjectSerializer;

/**
 * AddvideoservicecdnApiTest Class Doc Comment
 *
 * @category Class
 * @package  de\addvideo\client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AddvideoservicecdnApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addCDN
     *
     * Add a new CDN object.
     *
     */
    public function testAddCDN()
    {

    }

    /**
     * Test case for addCDNAccount
     *
     * Add a new CDNAccount object.
     *
     */
    public function testAddCDNAccount()
    {

    }

    /**
     * Test case for addCDNService
     *
     * Add a new CDNService object.
     *
     */
    public function testAddCDNService()
    {

    }

    /**
     * Test case for deleteCDN
     *
     * Delete CDN object matching the given id.
     *
     */
    public function testDeleteCDN()
    {

    }

    /**
     * Test case for deleteCDNAccount
     *
     * Delete CDNAccount object matching the given id.
     *
     */
    public function testDeleteCDNAccount()
    {

    }

    /**
     * Test case for deleteCDNService
     *
     * Delete CDNService object matching the given id.
     *
     */
    public function testDeleteCDNService()
    {

    }

    /**
     * Test case for getCDN
     *
     * Get CDN object for id.
     *
     */
    public function testGetCDN()
    {

    }

    /**
     * Test case for getCDNAccount
     *
     * Get CDNAccount object for id.
     *
     */
    public function testGetCDNAccount()
    {

    }

    /**
     * Test case for getCDNService
     *
     * Get CDNService object for id.
     *
     */
    public function testGetCDNService()
    {

    }

    /**
     * Test case for listCDNAccounts
     *
     * List CDNAccount objects depending on filter.
     *
     */
    public function testListCDNAccounts()
    {

    }

    /**
     * Test case for listCDNServices
     *
     * List CDNService objects depending on filter.
     *
     */
    public function testListCDNServices()
    {

    }

    /**
     * Test case for listCDNs
     *
     * List CDN objects depending on filter.
     *
     */
    public function testListCDNs()
    {

    }

    /**
     * Test case for updateCDN
     *
     * Update CDN object.
     *
     */
    public function testUpdateCDN()
    {

    }

    /**
     * Test case for updateCDNAccount
     *
     * Update CDNAccount object.
     *
     */
    public function testUpdateCDNAccount()
    {

    }

    /**
     * Test case for updateCDNService
     *
     * Update CDNService object.
     *
     */
    public function testUpdateCDNService()
    {

    }

}
