<?php
/**
 * AddvideoexportApiTest
 * PHP version 5
 *
 * @category Class
 * @package  de\addvideo\client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AddVideo REST API v1
 *
 * <h1>Willkommen bei AddVideo | add video to your project</h1><p>Nutzen Sie die Technologie von AddVideo zur Verbindung von CMS- mit CDN-Funktionalitäten. Mit AddVideo verarbeiten und distribuieren Sie Ihre Videoinhalte ganz nach Bedarf. Werden Sie und Ihre Anwendungen unabhängig von Oberflächen oder CDN-spezifischen Anforderungen. AddVideo bietet Ihnen:</p><ul><li>individuelle Nutzung durch Anbindung über Rest-API</li><li>Client SDKs in vielen Programmiersprachen frei verfügbar unter http://github.com/addvideo</li><li>Media Processing und Video Encoding Services</li><li>Betrieb und Datenhaltung in Rechenzentren in Deutschland</li><li>Service und Betrieb durch ein erfahrenes Team von Videospezialisten in Frankfurt am Main</li><li>einen stetig wachsenden Funktionsumfang</li><li>eine stetig wachsende Anzahl an angebundenen CDNs</li><li>Nutzung von zahlreichen OTT-Funktionen über die API</li></ul><p>Bei AddVideo können Sie individuell selbst entscheiden, welche Bausteine Sie für Ihre Videoverwaltung benötigen. Bestehende Systeme und Lösungen lassen sich komfortabel anbinden.</p>
 *
 * OpenAPI spec version: 1
 * Contact: info@addvideo.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace de\addvideo\client;

use \de\addvideo\client\Configuration;
use \de\addvideo\client\ApiClient;
use \de\addvideo\client\ApiException;
use \de\addvideo\client\ObjectSerializer;

/**
 * AddvideoexportApiTest Class Doc Comment
 *
 * @category Class
 * @package  de\addvideo\client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AddvideoexportApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addFTPCompletedExport
     *
     * Add a new FTPCompletedExport object.
     *
     */
    public function testAddFTPCompletedExport()
    {

    }

    /**
     * Test case for addFTPExportConfig
     *
     * Add a new FTPExportConfig object.
     *
     */
    public function testAddFTPExportConfig()
    {

    }

    /**
     * Test case for addS3CompletedExport
     *
     * Add a new S3CompletedExport object.
     *
     */
    public function testAddS3CompletedExport()
    {

    }

    /**
     * Test case for addS3ExportConfig
     *
     * Add a new S3ExportConfig object.
     *
     */
    public function testAddS3ExportConfig()
    {

    }

    /**
     * Test case for deleteFTPCompletedExport
     *
     * Delete FTPCompletedExport object matching the given id.
     *
     */
    public function testDeleteFTPCompletedExport()
    {

    }

    /**
     * Test case for deleteFTPExportConfig
     *
     * Delete FTPExportConfig object matching the given id.
     *
     */
    public function testDeleteFTPExportConfig()
    {

    }

    /**
     * Test case for deleteS3CompletedExport
     *
     * Delete S3CompletedExport object matching the given id.
     *
     */
    public function testDeleteS3CompletedExport()
    {

    }

    /**
     * Test case for deleteS3ExportConfig
     *
     * Delete S3ExportConfig object matching the given id.
     *
     */
    public function testDeleteS3ExportConfig()
    {

    }

    /**
     * Test case for getFTPCompletedExport
     *
     * Get FTPCompletedExport object for id.
     *
     */
    public function testGetFTPCompletedExport()
    {

    }

    /**
     * Test case for getFTPExportConfig
     *
     * Get FTPExportConfig object for id.
     *
     */
    public function testGetFTPExportConfig()
    {

    }

    /**
     * Test case for getS3CompletedExport
     *
     * Get S3CompletedExport object for id.
     *
     */
    public function testGetS3CompletedExport()
    {

    }

    /**
     * Test case for getS3ExportConfig
     *
     * Get S3ExportConfig object for id.
     *
     */
    public function testGetS3ExportConfig()
    {

    }

    /**
     * Test case for listFTPCompletedExports
     *
     * List FTPCompletedExport objects depending on filter.
     *
     */
    public function testListFTPCompletedExports()
    {

    }

    /**
     * Test case for listFTPExportConfigs
     *
     * List FTPExportConfig objects depending on filter.
     *
     */
    public function testListFTPExportConfigs()
    {

    }

    /**
     * Test case for listS3CompletedExports
     *
     * List S3CompletedExport objects depending on filter.
     *
     */
    public function testListS3CompletedExports()
    {

    }

    /**
     * Test case for listS3ExportConfigs
     *
     * List S3ExportConfig objects depending on filter.
     *
     */
    public function testListS3ExportConfigs()
    {

    }

    /**
     * Test case for updateFTPCompletedExport
     *
     * Update FTPCompletedExport object.
     *
     */
    public function testUpdateFTPCompletedExport()
    {

    }

    /**
     * Test case for updateFTPExportConfig
     *
     * Update FTPExportConfig object.
     *
     */
    public function testUpdateFTPExportConfig()
    {

    }

    /**
     * Test case for updateS3CompletedExport
     *
     * Update S3CompletedExport object.
     *
     */
    public function testUpdateS3CompletedExport()
    {

    }

    /**
     * Test case for updateS3ExportConfig
     *
     * Update S3ExportConfig object.
     *
     */
    public function testUpdateS3ExportConfig()
    {

    }

}
