<?php
/**
 * CrmcontractApiTest
 * PHP version 5
 *
 * @category Class
 * @package  de\addvideo\client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AddVideo REST API v1
 *
 * <h1>Welcome!</h1><p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p><p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam</p><p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
 *
 * OpenAPI spec version: 1
 * Contact: info@addvideo.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace de\addvideo\client;

use \de\addvideo\client\Configuration;
use \de\addvideo\client\ApiClient;
use \de\addvideo\client\ApiException;
use \de\addvideo\client\ObjectSerializer;

/**
 * CrmcontractApiTest Class Doc Comment
 *
 * @category Class
 * @package  de\addvideo\client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CrmcontractApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addContract
     *
     * Add a new Contract object.
     *
     */
    public function testAddContract()
    {

    }

    /**
     * Test case for addContractLine
     *
     * Add a new ContractLine object.
     *
     */
    public function testAddContractLine()
    {

    }

    /**
     * Test case for addContractType
     *
     * Add a new ContractType object.
     *
     */
    public function testAddContractType()
    {

    }

    /**
     * Test case for addCustomer
     *
     * Add a new Customer object.
     *
     */
    public function testAddCustomer()
    {

    }

    /**
     * Test case for deleteContract
     *
     * Delete Contract object matching the given id.
     *
     */
    public function testDeleteContract()
    {

    }

    /**
     * Test case for deleteContractLine
     *
     * Delete ContractLine object matching the given id.
     *
     */
    public function testDeleteContractLine()
    {

    }

    /**
     * Test case for deleteContractType
     *
     * Delete ContractType object matching the given id.
     *
     */
    public function testDeleteContractType()
    {

    }

    /**
     * Test case for deleteCustomer
     *
     * Delete Customer object matching the given id.
     *
     */
    public function testDeleteCustomer()
    {

    }

    /**
     * Test case for getContract
     *
     * Get Contract object for id.
     *
     */
    public function testGetContract()
    {

    }

    /**
     * Test case for getContractLine
     *
     * Get ContractLine object for id.
     *
     */
    public function testGetContractLine()
    {

    }

    /**
     * Test case for getContractType
     *
     * Get ContractType object for id.
     *
     */
    public function testGetContractType()
    {

    }

    /**
     * Test case for getCustomer
     *
     * Get Customer object for id.
     *
     */
    public function testGetCustomer()
    {

    }

    /**
     * Test case for listContractLines
     *
     * List ContractLine objects depending on filter.
     *
     */
    public function testListContractLines()
    {

    }

    /**
     * Test case for listContractTypes
     *
     * List ContractType objects depending on filter.
     *
     */
    public function testListContractTypes()
    {

    }

    /**
     * Test case for listContracts
     *
     * List Contract objects depending on filter.
     *
     */
    public function testListContracts()
    {

    }

    /**
     * Test case for listCustomers
     *
     * List Customer objects depending on filter.
     *
     */
    public function testListCustomers()
    {

    }

    /**
     * Test case for updateContract
     *
     * Update Contract object.
     *
     */
    public function testUpdateContract()
    {

    }

    /**
     * Test case for updateContractLine
     *
     * Update ContractLine object.
     *
     */
    public function testUpdateContractLine()
    {

    }

    /**
     * Test case for updateContractType
     *
     * Update ContractType object.
     *
     */
    public function testUpdateContractType()
    {

    }

    /**
     * Test case for updateCustomer
     *
     * Update Customer object.
     *
     */
    public function testUpdateCustomer()
    {

    }

}
