<?php
/**
 * CrmcontactApiTest
 * PHP version 5
 *
 * @category Class
 * @package  de\addvideo\client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AddVideo REST API v1
 *
 * <h1>Willkommen bei AddVideo | add video to your project</h1><p>Nutzen Sie die Technologie von AddVideo zur Verbindung von CMS- mit CDN-FunktionalitÃ¤ten. Mit AddVideo verarbeiten und distribuieren Sie Ihre Videoinhalte ganz nach Bedarf. Werden Sie und Ihre Anwendungen unabhÃ¤ngig von OberflÃ¤chen oder CDN-spezifischen Anforderungen. AddVideo bietet Ihnen:</p><ul><li>individuelle Nutzung durch Anbindung Ã¼ber Rest-API</li><li>Client SDKs in vielen Programmiersprachen frei verfÃ¼gbar unter http://github.com/addvideo</li><li>Media Processing und Video Encoding Services</li><li>Betrieb und Datenhaltung in Rechenzentren in Deutschland</li><li>Service und Betrieb durch ein erfahrenes Team von Videospezialisten in Frankfurt am Main</li><li>einen stetig wachsenden Funktionsumfang</li><li>eine stetig wachsende Anzahl an angebundenen CDNs</li><li>Nutzung von zahlreichen OTT-Funktionen Ã¼ber die API</li></ul><p>Bei AddVideo kÃ¶nnen Sie individuell selbst entscheiden, welche Bausteine Sie fÃ¼r Ihre Videoverwaltung benÃ¶tigen. Bestehende Systeme und LÃ¶sungen lassen sich komfortabel anbinden.</p>
 *
 * OpenAPI spec version: 1
 * Contact: info@addvideo.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace de\addvideo\client;

use \de\addvideo\client\Configuration;
use \de\addvideo\client\ApiClient;
use \de\addvideo\client\ApiException;
use \de\addvideo\client\ObjectSerializer;

/**
 * CrmcontactApiTest Class Doc Comment
 *
 * @category Class
 * @package  de\addvideo\client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CrmcontactApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addAddress
     *
     * Add a new Address object.
     *
     */
    public function testAddAddress()
    {

    }

    /**
     * Test case for addCompany
     *
     * Add a new Company object.
     *
     */
    public function testAddCompany()
    {

    }

    /**
     * Test case for addCompanyContact
     *
     * Add a new CompanyContact object.
     *
     */
    public function testAddCompanyContact()
    {

    }

    /**
     * Test case for addContact
     *
     * Add a new Contact object.
     *
     */
    public function testAddContact()
    {

    }

    /**
     * Test case for addCountry
     *
     * Add a new Country object.
     *
     */
    public function testAddCountry()
    {

    }

    /**
     * Test case for addTitle
     *
     * Add a new Title object.
     *
     */
    public function testAddTitle()
    {

    }

    /**
     * Test case for deleteAddress
     *
     * Delete Address object matching the given id.
     *
     */
    public function testDeleteAddress()
    {

    }

    /**
     * Test case for deleteCompany
     *
     * Delete Company object matching the given id.
     *
     */
    public function testDeleteCompany()
    {

    }

    /**
     * Test case for deleteCompanyContact
     *
     * Delete CompanyContact object matching the given id.
     *
     */
    public function testDeleteCompanyContact()
    {

    }

    /**
     * Test case for deleteContact
     *
     * Delete Contact object matching the given id.
     *
     */
    public function testDeleteContact()
    {

    }

    /**
     * Test case for deleteCountry
     *
     * Delete Country object matching the given id.
     *
     */
    public function testDeleteCountry()
    {

    }

    /**
     * Test case for deleteTitle
     *
     * Delete Title object matching the given id.
     *
     */
    public function testDeleteTitle()
    {

    }

    /**
     * Test case for getAddress
     *
     * Get Address object for id.
     *
     */
    public function testGetAddress()
    {

    }

    /**
     * Test case for getCompany
     *
     * Get Company object for id.
     *
     */
    public function testGetCompany()
    {

    }

    /**
     * Test case for getCompanyContact
     *
     * Get CompanyContact object for id.
     *
     */
    public function testGetCompanyContact()
    {

    }

    /**
     * Test case for getContact
     *
     * Get Contact object for id.
     *
     */
    public function testGetContact()
    {

    }

    /**
     * Test case for getCountry
     *
     * Get Country object for id.
     *
     */
    public function testGetCountry()
    {

    }

    /**
     * Test case for getTitle
     *
     * Get Title object for id.
     *
     */
    public function testGetTitle()
    {

    }

    /**
     * Test case for listAddresses
     *
     * List Address objects depending on filter.
     *
     */
    public function testListAddresses()
    {

    }

    /**
     * Test case for listCompanies
     *
     * List Company objects depending on filter.
     *
     */
    public function testListCompanies()
    {

    }

    /**
     * Test case for listCompanyContacts
     *
     * List CompanyContact objects depending on filter.
     *
     */
    public function testListCompanyContacts()
    {

    }

    /**
     * Test case for listContacts
     *
     * List Contact objects depending on filter.
     *
     */
    public function testListContacts()
    {

    }

    /**
     * Test case for listCountries
     *
     * List Country objects depending on filter.
     *
     */
    public function testListCountries()
    {

    }

    /**
     * Test case for listTitles
     *
     * List Title objects depending on filter.
     *
     */
    public function testListTitles()
    {

    }

    /**
     * Test case for updateAddress
     *
     * Update Address object.
     *
     */
    public function testUpdateAddress()
    {

    }

    /**
     * Test case for updateCompany
     *
     * Update Company object.
     *
     */
    public function testUpdateCompany()
    {

    }

    /**
     * Test case for updateCompanyContact
     *
     * Update CompanyContact object.
     *
     */
    public function testUpdateCompanyContact()
    {

    }

    /**
     * Test case for updateContact
     *
     * Update Contact object.
     *
     */
    public function testUpdateContact()
    {

    }

    /**
     * Test case for updateCountry
     *
     * Update Country object.
     *
     */
    public function testUpdateCountry()
    {

    }

    /**
     * Test case for updateTitle
     *
     * Update Title object.
     *
     */
    public function testUpdateTitle()
    {

    }

}
